export type Operator = {
  ref: string
  name: string
  eng_name: string
  founded?: number
  website?: string
  area:
    | 'nationwide'
    | 'central_southern'
    | 'northern'
    | 'southern'
    | 'central'
    | 'haifa'
    | 'jerusalem'
    | 'tel_aviv'
    | 'beersheba'
    | 'beit_shemesh'
  type: 'bus' | 'rail' | 'light_rail' | 'subway' | 'cable_car' | 'taxi'
}

export const operatorList: Operator[] = [
  {
    ref: '2',
    name: 'רכבת ישראל',
    eng_name: 'Israel Railways',
    founded: 1948,
    website: 'https://www.rail.co.il',
    area: 'nationwide',
    type: 'rail',
  },
  {
    ref: '3',
    name: 'אגד',
    eng_name: 'Egged',
    founded: 1933,
    website: 'https://www.egged.co.il',
    area: 'nationwide',
    type: 'bus',
  },
  {
    ref: '4',
    name: 'אלקטרה אפיקים תחבורה',
    eng_name: 'Electra Afikim Transport',
    founded: 2021,
    website: 'https://www.electra-afikim.co.il/',
    area: 'central_southern',
    type: 'bus',
  },
  {
    ref: '5',
    name: 'דן',
    eng_name: 'Dan Bus Company',
    founded: 1945,
    website: 'https://www.dan.co.il',
    area: 'central',
    type: 'bus',
  },
  {
    ref: '6',
    name: 'ש.א.מ',
    eng_name: 'United bus Services of Nazareth',
    founded: 1956,
    website: 'https://nazareth-unbs.com',
    area: 'northern',
    type: 'bus',
  },
  {
    ref: '7',
    name: 'נסיעות ותיירות',
    eng_name: 'Nazareth Travel and Tourism',
    founded: 1927,
    website: 'https://ntt-buses.com',
    area: 'northern',
    type: 'bus',
  },
  {
    ref: '8',
    name: 'גי.בי.טורס',
    eng_name: 'G.B. Tours',
    founded: 1943,
    website: 'https://gb-tours.com',
    area: 'northern',
    type: 'bus',
  },
  {
    ref: '10',
    name: 'מועצה אזורית אילות',
    eng_name: 'Eilot Regional Council',
    founded: 1964,
    website: 'https://www.eilot.org.il',
    area: 'southern',
    type: 'bus',
  },
  {
    ref: '14',
    name: 'נתיב אקספרס',
    eng_name: 'Nateev Express',
    founded: 2001,
    website: 'https://www.nateevexpress.com',
    area: 'northern',
    type: 'bus',
  },
  {
    ref: '15',
    name: 'מטרופולין',
    eng_name: 'Metropoline',
    founded: 2000,
    website: 'https://www.metropoline.com',
    area: 'central_southern',
    type: 'bus',
  },
  {
    ref: '16',
    name: 'סופרבוס',
    eng_name: 'Superbus',
    founded: 2000,
    website: 'https://www.superbus.co.il',
    area: 'nationwide',
    type: 'bus',
  },
  {
    ref: '18',
    name: 'קווים',
    eng_name: 'Kavim',
    founded: 2000,
    website: 'https://www.kavim-t.co.il',
    area: 'central',
    type: 'bus',
  },
  {
    ref: '20',
    name: 'כרמלית',
    eng_name: 'Carmelit',
    founded: 1959,
    website: 'https://www.carmelithaifa.com/',
    area: 'haifa',
    type: 'subway',
  },
  {
    ref: '21',
    name: 'כפיר',
    eng_name: 'Kfir Light Rail',
    founded: 2019,
    website: 'https://www.cfir.co.il',
    area: 'jerusalem',
    type: 'light_rail',
  },
  {
    ref: '22',
    name: 'תבל',
    eng_name: 'Tevel',
    founded: 2017,
    website: 'https://www.tevelmetro.co.il',
    area: 'tel_aviv',
    type: 'light_rail',
  },
  {
    ref: '23',
    name: 'גלים',
    eng_name: 'Galeem',
    founded: 1996,
    website: 'https://www.galeem.co.il',
    area: 'southern',
    type: 'bus',
  },
  {
    ref: '24',
    name: 'מועצה אזורית גולן',
    eng_name: 'Golan Regional Council',
    founded: 1979,
    website: 'https://www.golan.org.il',
    area: 'northern',
    type: 'bus',
  },
  {
    ref: '25',
    name: 'אלקטרה אפיקים',
    eng_name: 'Electra Afikim',
    founded: 2008,
    website: 'https://www.electra-afikim.co.il/',
    area: 'central_southern',
    type: 'bus',
  },
  {
    ref: '31',
    name: 'דן בדרום',
    eng_name: 'Dan BaDarom',
    founded: 2015,
    website: 'https://www.danbadarom.co.il/',
    area: 'southern',
    type: 'bus',
  },
  {
    ref: '32',
    name: 'דן באר שבע',
    eng_name: 'Dan Beersheba',
    founded: 2016,
    website: 'https://www.danbadarom.co.il/',
    area: 'beersheba',
    type: 'bus',
  },
  {
    ref: '33',
    name: 'כבל אקספרס',
    eng_name: 'Cable Express',
    founded: 2019,
    website: 'https://cableexpress.co/',
    area: 'jerusalem',
    type: 'cable_car',
  },
  {
    ref: '34',
    name: 'תנופה',
    eng_name: 'Tnufa',
    founded: 2019,
    area: 'central',
    website: 'https://www.tnufa-t.com/',
    type: 'bus',
  },
  {
    ref: '35',
    name: 'בית שמש אקספרס',
    eng_name: 'Beit Shemesh Express',
    founded: 2006,
    website: 'https://www.bs-exp.co.il/',
    area: 'beit_shemesh',
    type: 'bus',
  },
  {
    ref: '37',
    name: 'אקסטרה',
    eng_name: 'Extra Public Transportation',
    founded: 2020,
    website: 'https://extra-pt.co.il/',
    area: 'central',
    type: 'bus',
  },
  {
    ref: '38',
    name: 'אקסטרה ירושלים',
    eng_name: 'Extra Jerusalem',
    founded: 2020,
    website: 'https://extra-pt.co.il/',
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '40',
    name: 'יונייטד טורס',
    eng_name: 'United Tours',
    founded: 1960,
    area: 'nationwide',
    website: 'https://unitedtours.co.il/',
    type: 'bus',
  },
  {
    ref: '42',
    name: 'ירושלים - רמאללה איחוד',
    eng_name: 'Jerusalem - Ramallah Union',
    founded: undefined,
    website: 'https://www.ramallahbus.com/',
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '44',
    name: 'ירושלים - אבו-תור - ענאתא איחוד',
    eng_name: 'Jerusalem - Abu-Tor - Anata Union',
    founded: undefined,
    website: 'https://atabuses.com/',
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '45',
    name: 'ירושלים - אלווסט איחוד',
    eng_name: 'Jerusalem - Al-Wast Union',
    founded: undefined,
    website: undefined,
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '47',
    name: 'ירושלים - הר הזיתים',
    eng_name: 'Jerusalem - Mount of Olives',
    founded: undefined,
    website: 'https://mountofolivesbus.com/',
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '49',
    name: 'ירושלים - עיסאוויה מחנה שעפאט איחוד',
    eng_name: 'Jerusalem - Issawiya Shuafat Camp Union',
    founded: undefined,
    website: 'https://www.shufatbus.com/',
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '50',
    name: 'ירושלים - דרום איחוד',
    eng_name: 'Jerusalem - South Union',
    founded: undefined,
    website: 'https://south-buses.com/',
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '51',
    name: 'ירושלים - צור באהר איחוד',
    eng_name: 'Jerusalem - Tzur Baher Union',
    founded: undefined,
    website: undefined,
    area: 'jerusalem',
    type: 'bus',
  },
  {
    ref: '91',
    name: 'מוניות מטרו קו',
    eng_name: 'Metro Line Taxis',
    founded: undefined,
    area: 'tel_aviv',
    website: 'https://www.metrokav.com/',
    type: 'taxi',
  },
  {
    ref: '93',
    name: 'מוניות מאיה יצחק שדה',
    eng_name: 'Maya Yitzhak Sadeh Taxis',
    founded: undefined,
    website: undefined,
    area: 'tel_aviv',
    type: 'taxi',
  },
  {
    ref: '97',
    name: 'אודליה מוניות בעמ',
    eng_name: 'Odelia Taxis Ltd.',
    founded: undefined,
    website: undefined,
    area: 'central',
    type: 'taxi',
  },
  {
    ref: '98',
    name: 'מוניות רב קווית 4-5',
    eng_name: 'Multi-Line Taxis 4-5',
    founded: undefined,
    website: undefined,
    area: 'central',
    type: 'taxi',
  },
  {
    ref: '135',
    name: 'דרך אגד עוטף ירושלים',
    eng_name: 'Egged Jerusalem Envelope',
    founded: 2023,
    website: 'https://www.derechegged.co.il/',
    area: 'jerusalem',
    type: 'bus',
  },
]
