import { ComplainteField } from './ComplaintModalFields'

export const complaintTypes = [
  'no_ride',
  'no_stop',
  'delay',
  'overcrowded',
  'early',
  'add_or_remove_station',
  'add_new_line',
  'add_frequency',
  'driver_behavior',
  'cleanliness',
  'fine_appeal',
  'route_change',
  'line_switch',
  'station_signs',
  'ticketing_fares_discounts',
  'other',
  // 'train_delay',
  // 'train_no_ride',
  // 'train_early',
  // 'train_driver_behavior',
] as const

export type ComplaintType = (typeof complaintTypes)[number]

export const complaintTypeMappings: Record<ComplaintType, ComplainteField[]> = {
  no_ride: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  no_stop: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  delay: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  early: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  overcrowded: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  add_or_remove_station: [
    'busOperator',
    'activeDate',
    'lineNumber',
    'route',
    'addRemoveStationReason',
    'boardingStation',
    'requestedStationAddress',
    'travelFrom',
    'travelTo',
  ],
  add_new_line: ['cityFrom', 'cityTo'],
  add_frequency: [
    'addFrequencyReason',
    'busOperator',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  driver_behavior: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'wait',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
    'willingToTestifyMot',
    'willingToTestifyCourt',
  ],
  cleanliness: [
    'busOperator',
    'licensePlate',
    'eventDate',
    'eventTime',
    'lineNumber',
    'route',
    'travelFrom',
    'travelTo',
    'boardingStation',
  ],
  fine_appeal: [
    'ravKavNumber',
    'busOperator',
    'ticketDate',
    'ticketTime',
    'lineNumber',
    'route',
    'boardingStation',
    'travelFrom',
    'travelTo',
  ],
  route_change: ['busOperator', 'eventDate', 'lineNumber', 'route', 'travelFrom', 'travelTo'],
  line_switch: ['travelFrom', 'travelTo'],
  station_signs: [
    'busOperator',
    'eventDate',
    'eventTime',
    'cityFrom',
    'boardingAddress',
    // 'stationCatNum',
    // 'lineNumber',
  ],
  ticketing_fares_discounts: ['ravKavNumber'],
  other: [],
} as const
