name: Build
on: pull_request

env:
  ASSET_URL: https://s3.amazonaws.com/noam-gaash.co.il/${{ github.run_id }}/open-bus/${{ github.sha }}
  should_run: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.set_should_run.outputs.should_run }}
    steps:
      - name: Set should_run
        id: set_should_run
        if: env.should_run
        run: echo "::set-output name=should_run::true"

  build:
    runs-on: ubuntu-latest
    needs: [should_run]
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Run install
        run: npm ci
      - name: Build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  build-storybook:
    runs-on: ubuntu-latest
    needs: [should_run]
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Run install
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook -o dist/storybook
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/