name: Test Clean Tree
on:
  pull_request:
jobs:
  git-clean-tree-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18     
      - name: Install yarn
        run: npm install -g yarn     
      - name: make sure package.lock does not exist
        run: rm -f package-lock.json
      - name: Git Check Clean Tree
        uses: ArkadiK94/action-git-clean-tree@v1.0.3
        with:
          error-reason: "removing package-lock.json file"
      - name: Install dependencies
        run: yarn
      - name: Git Check Clean Tree
        uses: ArkadiK94/action-git-clean-tree@v1.0.3
        with:
          error-reason: "yarn"
      - name: Build
        run: yarn build
      - name: Git Check Clean Tree
        uses: ArkadiK94/action-git-clean-tree@v1.0.3
        with:
          error-reason: "yarn build"
      - name: Clean up
        if: always()
        run: npm uninstall -g yarn