name: Unit Tests
on:
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
    - name: run the tests
      run: yarn test:unit